FOSWIKI_ROOT?=~/foswiki/core
SUBDIRS=\
  droid-sans \
  droid-serif \
  lato \
  open-sans \
  oswald \
  roboto \
  roboto-mono \
  source-sans-pro \

include $(FOSWIKI_ROOT)/pub/System/NatSkin/Makefile.include

