FOSWIKI_ROOT?=~/foswiki/core
SUBDIRS=\
  dm-serif-display \
  dm-sans \
  droid-sans \
  droid-serif \
  lato \
  material-icons \
  montserrat \
  open-sans \
  open-sans-condensed \
  oswald \
  overpass \
  poppins \
  roboto \
  roboto-mono \
  roboto-condensed \
  source-code-pro \
  source-sans-pro \
  tabler-icons \
  titillium-web \
  work-sans \

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

