FOSWIKI_ROOT?=~/foswiki/core
SUBDIRS=\
  droid-sans \
  droid-serif \
  lato \
  open-sans \
  oswald \
  roboto \
  roboto-mono \
  source-sans-pro \
  source-code-pro \
  material-icons 

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

