#!/usr/bin/env perl

use strict;
use warnings;

my $iconFile = "./git/iconfont/codepoints";

open(my $fh, '<:encoding(UTF-8)', $iconFile)
  or die "Could not open file '$iconFile' $!";
 
print "<div class='overview'>\n";
while (my $row = <$fh>) {
  chomp $row;
  my $name;
  my $codepoint;
  if ($row =~ /^\s*(.*?)\s+(.*?)\s*$/) {
    $name = $1;
    $codepoint = $2
  } else {
    print STDERR "IGNORING $row\n";
    next;
  }

  $name =~ s/_/-/g;
  print "<a class='entry'><i class='ma ma-$name'></i> $name</a>\n";
}
print "</div>\n";
