#!/usr/bin/env perl

use strict;
use warnings;
use JSON;

my $iconFile = "./json.txt";

sub readFile {
  my $name = shift;

  my $data = '';
  my $IN_FILE;

  open($IN_FILE, '<', $name) || return;
  binmode $IN_FILE, ':encoding(utf-8)';
  
  local $/ = undef;
  $data = <$IN_FILE>;
  close($IN_FILE);
  $data = '' unless $data;

  return decode_json($data);
}

my $json = readFile($iconFile);
 
print "<div class='overview'>\n";
foreach my $icon (sort {$a->{name} cmp $b->{name}} @{$json->{icons}}) {
  my $id = $icon->{name};
  my $name = $id;
  $name =~ s/_/ /g;
  print "<a class='entry'><i class='ma'>$id</i> $name</a>\n";
}
print "</div>\n";
